# name: CI Pipeline

# on:
#   push:
#     branches: 
#       - main
#       - develop
#       - 'feature/**'
#       - 'release/**'
#       - 'hotfix/**'
#   pull_request:
#     branches: 
#       - main
#       - develop

# env:
#   NODE_VERSION: '18.x'

# jobs:
#   lint:
#     name: Code Quality
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ env.NODE_VERSION }}
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run lint
#         run: npm run lint || echo "Lint not configured"
#         continue-on-error: true

#   security-audit:
#     name: Security Check
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ env.NODE_VERSION }}
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run security audit
#         run: npm audit --audit-level high
#         continue-on-error: true

#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest
#     needs: lint
    
#     services:
#       mongodb:
#         image: mongo:6.0
#         ports:
#           - 27017:27017

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ env.NODE_VERSION }}
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Copy environment file
#         run: cp .env .env.test || echo ".env file not found"

#       - name: Wait for MongoDB
#         run: |
#           for i in {1..30}; do
#             if mongosh --host localhost:27017 --eval "db.adminCommand('ping')" >/dev/null 2>&1; then
#               echo "MongoDB ready"
#               break
#             fi
#             sleep 2
#           done

#       - name: Run tests
#         run: npm test || echo "No tests configured"
#         env:
#           NODE_ENV: test
#           MONGODB_URI: mongodb://mongo:27017/todolistDb

#   build:
#     name: Build Check
#     runs-on: ubuntu-latest
#     needs: [test, security-audit]
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ env.NODE_VERSION }}
#           cache: 'npm'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run build
#         run: npm run build || echo "No build script"

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: app-files
#           path: |
#             .
#             !node_modules
#             !.git
#           retention-days: 5